Vagrant.configure("2") do |c|
  c.ssh.insert_key = false
  c.vm.define 'centos-72-x64-master' do |v|
    v.vm.hostname = 'centos-72-x64-master'
    v.vm.box = 'puppetlabs/centos-7.2-64-nocm'
    v.vm.box_url = 'https://vagrantcloud.com/puppetlabs/boxes/centos-7.2-64-nocm'
    v.vm.box_check_update = 'true'
    v.vm.network :private_network, ip: "10.255.103.76", :netmask => "255.255.0.0", :mac => "08002770715A"
    v.vm.provider :virtualbox do |vb|
      vb.customize ['modifyvm', :id, '--memory', '4096', '--cpus', '1']
    end
  end
  c.vm.define 'centos-72-x64-agent' do |v|
    v.vm.hostname = 'centos-72-x64-agent'
    v.vm.box = 'puppetlabs/centos-7.2-64-nocm'
    v.vm.box_url = 'https://vagrantcloud.com/puppetlabs/boxes/centos-7.2-64-nocm'
    v.vm.box_check_update = 'true'
    v.vm.network :private_network, ip: "10.255.53.246", :netmask => "255.255.0.0", :mac => "080027502706"
    v.vm.provider :virtualbox do |vb|
      vb.customize ['modifyvm', :id, '--memory', '1024', '--cpus', '1']
    end
  end
end
